from collections.abc import Iterator
from typing import Any, NoReturn, TypeVar, overload

import numpy

from ..types import Numbertype

_T=TypeVar('_T')
class clear:
 def __init__(self)->None:'''コンソールを削除する。'''
class random:
 @classmethod
 def normal(
self,
loc:Numbertype=0,
scale:Numbertype=1,
lenght:int=1,
hierarchy:int=1
)->numpy.ndarray:'''指定された行数と列数分のランダムに生成された正規分布のnumpyの配列を返す。

 :param loc: 分布の平均値を指定する。
 :type loc: int
 :param scale: 分布の標準偏差を指定する。
 :type scale: int
 :param lenght: 生成される配列の列数を指定する。
 :type lenght: int
 :param hierarchy: 生成される配列の行数を指定する。
 :type hierarchy: int
 :return: 指定された行数と列数分の正規分布のnumpyの配列を返す。
 :rtype: numpy.ndarray'''
 @classmethod
 def rand(
cls,
mins:Numbertype=0,
maxs:Numbertype=1,
lenght:int=1,
hierarchy:int=1,
number:bool=True
)->numpy.ndarray:'''指定された行数と列数分のランダムに生成されたnumpyの配列を返す。

 :param mins: 生成される値の最低値を指定する。
 :type mins: Numbertype
 :param maxs: 生成される値の最大値を指定する。
 :type maxs: Numbertype
 :param lenght: 生成される配列の列数を指定する。
 :type lenght: int
 :param hierarchy: 生成される配列の行数を指定する。
 :type hierarchy: int
 :param number: ランダムに生成される値がint型(True)かfloat型(False)かを指定する。
 :type number: bool
 :return: 指定された行数と列数分のnumpyの配列を返す。
 :rtype: numpy.ndarray'''
class sort:
 __static_attributes__:tuple[str]
 __class__:type
 __firstlineno__:int
 @overload
 def __init__(self,data:list|tuple|LIST,type:bool=True)->None:'''配列内の要素を昇順で並べ変える。

 :param data: 並べ替えたい配列を指定する。
 :type data: list|tuple|LIST
 :param type: 昇順(True)か降順(False)かを指定する。
 :type type: bool'''
 @overload
 def __init__(self,data:list|tuple|LIST,type:bool=False)->None:'''配列内の要素を降順で並べ変える。

 :param data: 並べ替えたい配列を指定する。
 :type data: list|tuple|LIST
 :param type: 昇順(True)か降順(False)かを指定する。
 :type type: bool'''
 def __dir__(self)->list:...
 def __delattr__(self):...
 def __getattribute__(self):...
 @classmethod
 def __instancecheck__(cls,ins)->bool:...
 def __contains__(self,val:Any)->bool:...
 def __iter__(self):...
 def __bool__(self)->bool:...
 def __len__(self)->int:...
 def __reversed__(self)->sort:...
class LIST:
 __static_attributes__:tuple[str]
 __class__:type
 __firstlineno__:int
 def __init__(self,lists:list|tuple|range|numpy.ndarray,*arg:tuple)->None:'''配列を作成する。'''
 def __add__(self,val:list|tuple|LIST)->LIST:...
 def __radd__(self,val:list|tuple|LIST)->LIST:...
 def __iadd__(self,val:Any)->LIST:...
 def __mul__(self,val:int)->LIST:...
 def __contains__(self,val)->bool:...
 def __len__(self)->int:...
 def __iter__(self)->Iterator[_T]:...
 def __reversed__(self)->LIST:...
 def __eq__(self,lists:LIST)->bool:...
 def __ne__(self,lists:LIST)->bool:...
 @classmethod
 def __instancecheck__(cls,ins)->bool:...
 @overload
 def __getitem__(self,val:int)->_T:...
 @overload
 def __getitem__(self,val:slice)->list:...
 def __dir__(self)->list:...
 def __delattr__(self):...
 def __getattribute__(self):...
 def flatten(self)->list:'''多次元配列を一次元配列に変換する。'''
 def get(self,val:int)->list:...
 def append(self,*arg:tuple)->None:...
 def clear(self)->NoReturn:'''LISTの要素を削除する。'''
 @overload
 def sort(self,type:bool=True)->LIST:'''LISTの要素を昇順で並べ替える。'''
 @overload
 def sort(self,type:bool=False)->LIST:'''LISTの要素を降順で並べ替える。'''
class Number:
 __static_attributes__:tuple[str]
 __class__:type
 __firstlineno__:int
 def __init__(self,val:int|float|Number)->None:'''数値に関するクラス

 :param val: 数値を指定する。
 :type val: int|float|Number
 :raises TypeError: 数値以外を指定した場合に発生させる。'''
 def __dir__(self)->list:...
 def __delattr__(self):...
 def __getattribute__(self):...
 @classmethod
 def __instancecheck__(cls,ins)->bool:...
 def __int__(self)->int:...
 def __float__(self)->float:...
 def __str__(self)->str:...
 def __add__(self,val:int|float|Number)->Number:...
 def __sub__(self,val:int|float|Number)->Number:...
 def __mul__(self,val:int|float|Number)->Number:...
 def __pow__(self,val:int|float|Number)->Number:...
 def __ipow__(self,val:int|float|Number)->Number:...
 def __truediv__(self,val:int|float|Number)->Number:...
 def __pow__(self,val:int|float|Number)->Number:...
 def __ipow__(self,val:int|float|Number)->Number:...
 def __radd__(self,val:int|float|Number)->Number:...
 def __rsub__(self,val:int|float|Number)->Number:...
 def __rmul__(self,val:int|float|Number)->Number:...
 def __rtruediv__(self,val:int|float|Number)->Number:...
 def __floordiv__(self,val:int|float|Number)->Number:...
 def __iadd__(self,val:int|float|Number)->Number:...
 def __isub__(self,val:int|float|Number)->Number:...
 def __imul__(self,val:int|float|Number)->Number:...
 def __itruediv__(self,val:int|float|Number)->Number:...
 def __eq__(self,val:int|float|Number)->bool:...
 def __ne__(self,val:int|float|Number)->bool:...
 def __lt__(self,val:int|float|Number)->bool:...
 def __le__(self,val:int|float|Number)->bool:...
 def __gt__(self,val:int|float|Number)->bool:...
 def __ge__(self,val:int|float|Number)->bool:...
 def __abs__(self)->Number:...
 def __round__(self,n:int=0):...
 def __ceil__(self)->Number:...
 def __floor__(self)->Number:...
 def __neg__(self)->Number:...
 def __pos__(self)->Number:...
 def __dir__(self)->list:...
 def __sizeof__(self)->int:...
class zips:
 def __init__(self,iterables:tuple|list=(),fillvalues:tuple|list=())->None:'''iterablesのzipを返す。

 :param iterables: 繰り返す配列を指定する。
 :type iterables: tuple|list
 :param fillvalues: `iterables`で要素の数が足りない時に追加する値を指定する。
 :type fillvalues: tuple|list'''
 def __iter__(self):...