from collections.abc import Iterator
from typing import Any

import numpy as np

from ....nparray import NPArray

__all__ = ["getLabel"]

class getLabel(NPArray):
    def __init__(self, label: list | tuple | np.ndarray | None = None) -> None: ...
    def __iter__(self) -> Iterator[Any | None]: ...
    def __getitem__(self, val: int) -> Any: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def loop(self, lenght: int) -> getLabel: ...
