from typing import Any

import numpy as np

__all__ = [
    "bol",
    "bols",
    "listchose",
    "list2float",
    "list2number",
    "num0",
    "num0s",
    "num1s",
    "range_zero_one",
]

def range_zero_one(val: float, out: float = 1.0, endpoint: bool = True) -> float: ...
def num1s(val: np.number = 0, mins: np.number = 1) -> int | float: ...
def num0s(val: np.number = 0, mins: np.number = 0) -> int | float: ...
def num0(val: np.number = 0, mins: np.number = 0) -> int | float: ...
def list2float(lin: list[Any] | tuple[Any] = None) -> bool: ...
def listchose(val: str, arr: list, other: str | None = None) -> str: ...
def bols(bools: bool = ..., trus: Any = None, fals: Any = None) -> Any: ...
def bol(vals: bool = ..., other: bool = False) -> bool: ...
