from collections.abc import Iterator
from typing import Literal
from ....types import Numbertype
__all__:list
class Hatch:
 '''塗りつぶすアイコンの設定に関するクラス'''
 def __init__(
self,
hatch:Literal[None,'o','oo','O','OO','x','xx','*','**','*-','+','++','+o','-','--','-\\\\','.','..','/','//','/o','O.','O|','\\','\\\\','\\|','o-','x*','|','|*','||']=None
)->None:...
 def __iter__(self)->Iterator[str,None]:...
 def __len__(self)->int:...
 def __str__(self)->str:...
class NSolid:
 '''グラフ内の線の設定に関するクラス'''
 def __init__(
self,
solid:Literal['dashdot','dashed','dotted','none',None,'None','solid','',' ','-','--','-.',':']=None
)->None:...
 def __iter__(self)->Iterator[str,None]:...
 def __len__(self)->int:...
 def __str__(self)->str:...
class Solid:
 '''グラフ内の線の設定に関するクラス'''
 def __init__(
self,
solid:Literal['dashdot','dashed','dotted','solid','-','--','-.',':']='solid'
)->None:...
 def __iter__(self)->Iterator[str,None]:...
 def __len__(self)->int:...
 def __str__(self)->str:...
class Marker:
 '''マーカーの設定に関するクラス'''
 def __init__(
self,
marker:Literal[0,1,2,3,4,5,6,7,8,9,10,11,'1','2','3','4','8','d','D','h','H','o','p','P','s','v','x','X','$\\alpha$','$\\beta$','$\\gamma$','*','+',',','.','<','>','^','_','|']=None
)->None:...
 def __iter__(self)->Iterator[str,int,None]:...
 def __len__(self)->int:...
 def __str__(self)->str:...
class SCapstyle:
 '''実線の端点の形状を設定する。'''
 def __init__(
self,
style:Literal['butt','projecting','round']='butt'
)->None:...
 def __iter__(self)->Iterator[str]:...
 def __len__(self)->int:...
 def __str__(self)->str:...
class Angle:
 '''角度をサポートする。'''
 def __init__(
self,
val:Numbertype,
now:Literal['degrees','radian']='degrees',
do:Literal['radian','degrees']='radian'
)->None:...
 def __int__(self)->int:...
 def __float__(self)->float:...
class FMT:
 def __init__(
self,
marker:Literal['.','s','o','p','v','*','^','D']=None,
line:Literal['dashdot','dashed','dotted','solid','-','--','-.',':']=None,
color:Literal['b','c','g','k','m','r','w','y']=None
)->None:...
 def __str__(self)->str:...