"""グラフの線を設定するモジュール"""

from collections.abc import Iterator

from ....nparray import NPString
from ...typing import Type_Solid

__all__ = ["Solid", "Solidlist"]

class Solid:
    def __init__(self, solid: Type_Solid = "-") -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def solid(self) -> str: ...

class Solidlist(NPString):
    def __init__(self, solid: Type_Solid | tuple[Type_Solid, ...] = "-") -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: int) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
